version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/posgresql/data
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        while !</dev/tcp/db/5432; do sleep 1; done;
        python manage.py makemigrations        
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev.local
    depends_on:
      - db

volumes:
  postgres_data:
